// version.h — the version this firmware was built for.
//
// GENERATED by spi_bridge/tools/make_version.py from spi_bridge/version.py — do not edit; change version.py and
// re-run the script. The firmware logs it at boot and warns if the Radxa reports a different one.

#ifndef KYPHONE_VERSION_H
#define KYPHONE_VERSION_H

#define KYPHONE_VERSION "0.3.0"

#endif  // KYPHONE_VERSION_H
