#!/usr/bin/env python3
"""Generate spi_bridge/reader_fonts.py from the FreeSerif headers the firmware draws with.

The Inkplate draws book text with Adafruit GFX fonts (spi_bridge/Inkplate_SPI_Peripheral/fonts/*.h). The Radxa
has to know exactly how wide every glyph draws so it can wrap lines and pack pages, and the emulator draws the
very same glyph bitmaps, so this script reads those headers (the single source of truth) and writes a plain
Python module with each font's line height and, for printable ASCII, every glyph's metrics and bitmap.

    python3 spi_bridge/tools/make_reader_fonts.py            # regenerate reader_fonts.py
    python3 spi_bridge/tools/make_reader_fonts.py --check    # exit 1 if it is out of date (a test does this)

Header format (Adafruit GFX): a byte array of packed glyph bitmaps, a table of
{bitmapOffset, width, height, xAdvance, xOffset, yOffset} per glyph, and a GFXfont {bitmap, glyph, first, last,
yAdvance}. A glyph's bitmap is width*height bits, row after row with no padding, most significant bit first.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(HERE, '..', 'Inkplate_SPI_Peripheral', 'fonts')
OUT_PY = os.path.join(HERE, '..', 'reader_fonts.py')

# size letter on the wire -> (point size, header base name). Order is smallest to largest.
SIZES = [('S', 9), ('M', 12), ('L', 18), ('X', 24)]


def parse_header(text, name):
    """-> (first, last, y_advance, glyphs) where glyphs is a list of (offset, w, h, x_advance, x_offset, y_offset)
    and the bitmap is returned as a list of byte values."""
    bitmaps = re.search(r'%sBitmaps\[\]\s*PROGMEM\s*=\s*\{(.*?)\};' % name, text, re.S)
    glyphs = re.search(r'%sGlyphs\[\]\s*PROGMEM\s*=\s*\{(.*?)\};' % name, text, re.S)
    font = re.search(r'GFXfont\s+%s\s+PROGMEM\s*=\s*\{.*?Glyphs,\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+),\s*(\d+)\}' % name,
                     text, re.S)
    if not (bitmaps and glyphs and font):
        raise ValueError('cannot parse %s' % name)
    data = [int(x, 16) for x in re.findall(r'0x[0-9A-Fa-f]{2}', bitmaps.group(1))]
    table = [tuple(int(v) for v in m) for m in re.findall(
        r'\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}', glyphs.group(1))]
    first, last, y_adv = int(font.group(1), 16), int(font.group(2), 16), int(font.group(3))
    if len(table) != last - first + 1:
        raise ValueError('%s: %d glyphs for range %d..%d' % (name, len(table), first, last))
    return first, last, y_adv, table, data


def glyph_bytes(data, offset, w, h):
    n = (w * h + 7) // 8
    chunk = data[offset:offset + n]
    if len(chunk) != n:
        raise ValueError('bitmap runs past the end of the font data')
    return ''.join('%02x' % b for b in chunk)


def render():
    lines = [
        '"""Book fonts for the reader: FreeSerif at 9, 12, 18 and 24 points, as the Inkplate draws them.',
        '',
        'GENERATED by spi_bridge/tools/make_reader_fonts.py from Inkplate_SPI_Peripheral/fonts/*.h - do not edit;',
        'change the script and re-run it. Glyph data: GNU FreeFont via Adafruit GFX (spi_bridge/assets/freeserif-NOTICE.txt).',
        '',
        'FONTS[size] with size in SIZES (S M L X):',
        "    'points'     point size",
        "    'y_advance'  pixels from one baseline to the next (GFX yAdvance)",
        "    'glyphs'     {char code: (width, height, x_advance, x_offset, y_offset, bitmap hex)} for 0x20..0x7E;",
        '                 the bitmap is width*height bits, rows packed with no padding, most significant bit first,',
        '                 drawn with its top-left at (cursor x + x_offset, baseline + y_offset).',
        '"""',
        '',
        'SIZES = %r' % (tuple(s for s, _p in SIZES),),
        '',
        'FONTS = {',
    ]
    for size, points in SIZES:
        name = 'FreeSerif%dpt7b' % points
        with open(os.path.join(FONT_DIR, name + '.h')) as f:
            first, last, y_adv, table, data = parse_header(f.read(), name)
        lines.append('    %r: {' % size)
        lines.append("        'points': %d, 'y_advance': %d," % (points, y_adv))
        lines.append("        'glyphs': {")
        for code, (off, w, h, xa, xo, yo) in zip(range(first, last + 1), table):
            lines.append('            %d: (%d, %d, %d, %d, %d, %r),' % (code, w, h, xa, xo, yo, glyph_bytes(data, off, w, h)))
        lines.append('        },')
        lines.append('    },')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def main(argv):
    text = render()
    if '--check' in argv:
        if not os.path.exists(OUT_PY) or open(OUT_PY).read() != text:
            print('out of date (run make_reader_fonts.py): reader_fonts.py')
            return 1
        print('reader fonts up to date')
        return 0
    with open(OUT_PY, 'w') as f:
        f.write(text)
    print('wrote', os.path.relpath(OUT_PY))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
