#!/usr/bin/env python3
"""Generate the emoji bitmaps drawn in received texts, from GNU Unifont's 16x16 monochrome glyphs.

The panel draws only ASCII, so a received emoji travels as ONE byte: the 127 byte values from 0x80 to 0xFF,
leaving out 0xB7 (the wire's sub-field separator). EMOJI below is the chosen set, in code order; ALIASES map
other code points (older symbol forms) onto one of them. Anything else stays '?' (kyphone_os.sanitize).

Each emoji is one 16x16 drawing. In a bubble (textSize 3, an 18x24 character cell) it fills exactly one character;
in the texts-list preview (textSize 2, a 12x16 cell) the Radxa sends it followed by a space, so it has two cells
(shrinking it to 12x12 was tried and looked muddy).

Glyphs: GNU Unifont 18.0.01 (unifoundry.com), dual-licensed; used here under the SIL Open Font License 1.1 (see
spi_bridge/assets/unifont-NOTICE.txt). Only the glyphs used are kept, in spi_bridge/assets/unifont-emoji.hex.

Writes two files from that one source:
    spi_bridge/Inkplate_SPI_Peripheral/ui_emoji.h   C arrays for the firmware (Adafruit GFX drawBitmap format)
    spi_bridge/emoji_table.py                       the code table and bitmaps for kyphone_os.py and simulator.py

    python3 spi_bridge/tools/make_emoji.py                        # regenerate both from the vendored glyphs
    python3 spi_bridge/tools/make_emoji.py --check                # exit 1 if either file is out of date (a test does this)
    python3 spi_bridge/tools/make_emoji.py --from unifont.hex unifont_upper.hex   # re-extract the vendored glyphs
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GLYPHS = os.path.join(ROOT, 'assets', 'unifont-emoji.hex')
HEADER = os.path.join(ROOT, 'Inkplate_SPI_Peripheral', 'ui_emoji.h')
TABLE = os.path.join(ROOT, 'emoji_table.py')

# The most used emoji (roughly by published usage rankings), 127 of them: one per free byte code.
EMOJI = ('😂 ❤ 🤣 👍 😭 🙏 😘 🥰 😍 😊 🎉 😁 💕 🥺 😅 🔥 🤦 🤷 🙄 😆 🤗 😉 🎂 🤔 👏 🙂 😳 🥳 😎 👌 💜 😔 '
         '💪 ✨ 💖 👀 😋 😏 😢 👉 💗 😩 💯 🌹 💞 🎈 💙 😃 😡 💐 😜 🙈 😄 🤤 🙌 🤪 ❣ 😀 💋 💀 👇 💔 😌 💓 🤩 '
         '🙃 😬 😱 😴 🤭 😐 🌞 😒 😇 🌸 😈 🎶 ✌ 🎊 🥵 😞 💚 🖤 💰 😚 👑 🎁 💥 🙋 😑 🥴 👈 💩 ✅ 👋 🤞 😠 '
         '😕 🤫 🌈 ⭐ 😷 🤓 😝 🎄 🍕 ☕ 🐶 🐱 🏠 🙁 😮 😤 🤯 🥲 👎 🎵 ❌ ❓ ❗ 🌙 🤍 🧡 💛 😛 🤝 👻').split()
ALIASES = {'☺': '🙂', '♥': '❤', '☀': '🌞', '☹': '🙁'}
CODES = [b for b in range(0x80, 0x100) if b != 0xB7]


def load_glyphs(paths):
    glyphs = {}
    for path in paths:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if ':' in line:
                    cp, h = line.split(':')
                    glyphs[int(cp, 16)] = h
    return glyphs


def rows16(h):
    """A Unifont hex glyph as 16 rows of 16 bits (an 8-wide glyph is centred)."""
    if len(h) == 32:
        return [int(h[i:i + 2], 16) << 4 for i in range(0, 32, 2)]
    return [int(h[i:i + 4], 16) for i in range(0, 64, 4)]


def build(glyphs):
    assert len(EMOJI) == len(CODES) == 127, (len(EMOJI), len(CODES))
    assert len(set(EMOJI)) == len(EMOJI)
    table, b16 = {}, []
    for e, code in zip(EMOJI, CODES):
        cp = ord(e)
        if cp not in glyphs:
            raise SystemExit('Unifont has no glyph for U+%04X %s' % (cp, e))
        r = rows16(glyphs[cp])
        table[cp] = code
        b16.append(r)
    for alias, target in ALIASES.items():
        table[ord(alias)] = table[ord(target)]

    py = ['# Generated by tools/make_emoji.py from GNU Unifont (SIL OFL 1.1; see assets/unifont-NOTICE.txt). Do not edit.',
          '# CODES: emoji code point -> the one byte that carries it on the wire. BITMAPS16: byte -> 16 rows of',
          '# 16 pixels, most significant bit leftmost.', '',
          'CODES = {']
    py += ['    0x%X: 0x%02X,' % (cp, code) for cp, code in sorted(table.items())]
    py += ['}', '', 'BITMAPS16 = {']
    py += ['    0x%02X: (%s),' % (code, ', '.join('0x%04X' % v for v in r)) for code, r in zip(CODES, b16)]
    py += ['}', '']

    h = ['// Generated by tools/make_emoji.py from GNU Unifont (SIL OFL 1.1; see assets/unifont-NOTICE.txt). Do not edit.',
         '// Emoji in received texts: byte codes 0x80-0xFF except 0xB7, in order. Adafruit GFX drawBitmap format.',
         '#pragma once', '',
         '#define UI_EMOJI_COUNT %d' % len(CODES), '',
         'static const uint8_t ui_emoji16[UI_EMOJI_COUNT][32] PROGMEM = {']
    for e, r in zip(EMOJI, b16):
        h.append('    {%s},   // U+%04X' % (', '.join('0x%02X,0x%02X' % (v >> 8, v & 0xFF) for v in r), ord(e)))
    h += ['};', '',
          '// The emoji a wire byte stands for, or -1 for an ordinary character.',
          'static inline int ui_emoji_index(unsigned char c) {',
          '    if (c < 0x80 || c == 0xB7) return -1;',
          '    int i = c - 0x80 - (c > 0xB7 ? 1 : 0);',
          '    return i < UI_EMOJI_COUNT ? i : -1;',
          '}', '']
    return '\n'.join(py), '\n'.join(h)


def main(argv):
    if argv[:1] == ['--from']:
        glyphs = load_glyphs(argv[1:])
        wanted = sorted({ord(e) for e in EMOJI})
        with open(GLYPHS, 'w') as f:
            for cp in wanted:
                f.write('%06X:%s\n' % (cp, glyphs[cp]))
        print('wrote %s (%d glyphs)' % (GLYPHS, len(wanted)))
        argv = []
    py, h = build(load_glyphs([GLYPHS]))
    if '--check' in argv:
        stale = []
        for path, text in ((TABLE, py), (HEADER, h)):
            try:
                with open(path) as f:
                    if f.read() != text:
                        stale.append(path)
            except OSError:
                stale.append(path)
        for path in stale:
            print('out of date: %s (run tools/make_emoji.py)' % path)
        return 1 if stale else 0
    for path, text in ((TABLE, py), (HEADER, h)):
        with open(path, 'w') as f:
            f.write(text)
    print('wrote %s and %s' % (TABLE, HEADER))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
