#!/usr/bin/env python3
"""Generate Inkplate_SPI_Peripheral/version.h from spi_bridge/version.py, so the firmware knows the version it was built for.

    python3 spi_bridge/tools/make_version.py            # write version.h
    python3 spi_bridge/tools/make_version.py --check    # exit 1 if it is out of date (a test does this)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..'))
import version  # noqa: E402

OUT_H = os.path.join(HERE, '..', 'Inkplate_SPI_Peripheral', 'version.h')


def render():
    return ('// version.h — the version this firmware was built for.\n'
            '//\n'
            '// GENERATED by spi_bridge/tools/make_version.py from spi_bridge/version.py — do not edit; change version.py and\n'
            '// re-run the script. The firmware logs it at boot and warns if the Radxa reports a different one.\n'
            '\n'
            '#ifndef KYPHONE_VERSION_H\n'
            '#define KYPHONE_VERSION_H\n'
            '\n'
            '#define KYPHONE_VERSION "%s"\n'
            '\n'
            '#endif  // KYPHONE_VERSION_H\n') % version.VERSION


def main(argv):
    text = render()
    if '--check' in argv:
        if not os.path.exists(OUT_H) or open(OUT_H).read() != text:
            print('out of date (run make_version.py): version.h')
            return 1
        print('version.h up to date (%s)' % version.VERSION)
        return 0
    with open(OUT_H, 'w') as f:
        f.write(text)
    print('wrote', os.path.relpath(OUT_H), '(%s)' % version.VERSION)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
